# Generated by Django 2.0 on 2020-08-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
