# Generated by Django 2.0 on 2020-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0003_auto_20200819_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='song',
            field=models.FileField(null=True, upload_to='static/upload'),
        ),
    ]
