# Generated by Django 2.0 on 2020-08-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0004_auto_20200820_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='song',
            field=models.FileField(null=True, upload_to='upload'),
        ),
    ]
