# Generated by Django 2.0 on 2020-08-21 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0005_auto_20200820_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='song',
        ),
        
    ]
