# Generated by Django 2.0 on 2020-08-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0006_auto_20200821_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='album',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='artist',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='cover',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='encodedBy',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='genre',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='lyrics',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='release',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
