# Generated by Django 2.0 on 2020-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0007_auto_20200821_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='duration',
        ),
    ]
