# Generated by Django 2.0 on 2020-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0008_remove_audiofile_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
