# Generated by Django 2.0 on 2020-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0009_audiofile_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='cloudSrc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
