# Generated by Django 2.0 on 2020-08-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0011_remove_audiofile_encodedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
