# -*- coding: utf8 -*-

"""
Django settings for song project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import dj_database_url


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ya5gupgvq^_ysq3y1%6l=+d=slk^5=)i!fyo#(%plor7pmf*te'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # development
# DEBUG = False # production

ALLOWED_HOSTS = ['127.0.0.1', '.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_celery_beat', # 로컬에서만 테스트하기
    # 'django_celery_results', # 로컬에서만 테스트하기
    'mp3', # 프로젝트 폴더
]

# MIDDLE엄E_CLASS 에서 변경함 => 장고 버전 업그레이드
# 제대로 작성되지 않으면 정적파일 로드가 되지 않음
# 깃이 충돌하면서 미들웨어 코드가 깨져서  static 파일들을 읽어오지 못했음
MIDDLEWARE= [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'song.urls' # URL을 song 폴더부터 읽기 시작함
# ROOT_URLCONF = 'mp3.urls' # 이렇게 설정하면 song.urls 파일은 동작하지 않음

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'static')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'song.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#  NAME: DB 이름
# USER: createsuperuser 로 설정한 ID
# PASSWORD: createsuperuser 로 설정한 비밀번호
# HOST: 사이트 주소
# 포트 : 기본 3306
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # production
        # 'ENGINE': 'django.db.backends.sqlite3',    # development
        'NAME': 'music',
        'USER': 'syleemomo',
        'PASSWORD': 'rkrrlsk',
        'HOST': 'https://sylee-music-player.herokuapp.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# 개발자 환경에서 static 폴더 인식은 django 상위버전에서
# 아래와 같이 STATICFILES_DIRS 변수 내 배열로 셋팅해야 인식함

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 로컬에서 테스트할때만 필요하고 프로덕션인 경우에는 AWS S3나 구글 파이어베이스 스토리지 사용하기
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# AUTH_USER_MODEL = 'users.Users' # 'AppName.모델명'


# 로컬에서만 테스트하기
#config/settings.py
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Asia/Seoul'
# CELERY_TASK_TRACK_STARTED=True

